# Generated by Django 4.2.1 on 2023-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinanceMetrics", "0003_remove_aaplstock_close_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aaplstock",
            name="live_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="live_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="live_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="live_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="live_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="live_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="live_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
