# Generated by Django 4.2.1 on 2023-05-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinanceMetrics", "0004_aaplstock_live_price_amznstock_live_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aaplstock",
            name="percent_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="percent_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="percent_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="percent_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="percent_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="percent_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="percent_change",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
