# Generated by Django 4.2.1 on 2023-05-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "FinanceMetrics",
            "0005_aaplstock_percent_change_amznstock_percent_change_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aaplstock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aaplstock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aaplstock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aaplstock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aaplstock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aaplstock",
            name="price_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aaplstock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="price_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="amznstock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="price_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googstock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="price_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metastock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="price_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="msftstock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="price_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nflxstock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="close_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="high_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="low_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="open_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="previous_close",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="price_change",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tslastock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
