# Generated by Django 4.2.1 on 2023-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinanceMetrics", "0006_aaplstock_close_price_aaplstock_high_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="commodities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crudeoil", models.FloatField()),
                ("natgas", models.FloatField()),
                ("copper", models.FloatField()),
                ("aluminum", models.FloatField()),
                ("wheat", models.FloatField()),
            ],
        ),
    ]
