# Generated by Django 4.2.1 on 2023-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinanceMetrics", "0007_commodities"),
    ]

    operations = [
        migrations.CreateModel(
            name="news",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("summary", models.CharField(max_length=1000)),
                ("urlToImage", models.CharField(max_length=1000)),
                ("publishedAt", models.CharField(max_length=1000)),
            ],
        ),
    ]
