# Generated by Django 4.2.1 on 2023-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinanceMetrics", "0009_newscollection"),
    ]

    operations = [
        migrations.CreateModel(
            name="news2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("summary", models.CharField(max_length=1000)),
                ("urlToImage", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="news3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("summary", models.CharField(max_length=1000)),
                ("urlToImage", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="news4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("summary", models.CharField(max_length=1000)),
                ("urlToImage", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="news5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("url", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("summary", models.CharField(max_length=1000)),
                ("urlToImage", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name="news",
            new_name="news1",
        ),
        migrations.RenameField(
            model_name="news1",
            old_name="publishedAt",
            new_name="source",
        ),
        migrations.DeleteModel(
            name="NewsCollection",
        ),
    ]
