# Generated by Django 4.2.1 on 2023-06-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FinanceMetrics", "0010_news2_news3_news4_news5_rename_news_news1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EUR", models.FloatField()),
                ("GBP", models.FloatField()),
                ("JPY", models.FloatField()),
                ("CAD", models.FloatField()),
            ],
        ),
    ]
