# Generated by Django 4.2.1 on 2023-06-04 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("FinanceMetrics", "0012_currency_inr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commodities",
            old_name="copper",
            new_name="gold",
        ),
        migrations.RenameField(
            model_name="commodities",
            old_name="crudeoil",
            new_name="oil",
        ),
        migrations.RenameField(
            model_name="commodities",
            old_name="natgas",
            new_name="petrol",
        ),
        migrations.RenameField(
            model_name="commodities",
            old_name="wheat",
            new_name="silver",
        ),
    ]
