# Generated by Django 4.1.10 on 2023-08-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceMetrics', '0014_news6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodities',
            old_name='aluminum',
            new_name='aluminium',
        ),
    ]
