name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          API_KEY_1: ${{ secrets.API_KEY }}
          API_KEY_2: ${{ secrets.NINJAAPI_KEY }}
          API_KEY_3: ${{ secrets.TWELVEDATAAPI_KEY }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/financemetrics:${{ github.sha }} \
            --build-arg API_KEY=$API_KEY_1 \
            --build-arg NINJAAPI_KEY=$API_KEY_2 \
            --build-arg TWELVEDATAAPI_KEY=$API_KEY_3 .
          docker push -t $DOCKERHUB_USERNAME/financemetrics:${{ github.sha }}
