name: Trigger auto deployment for financemetricscontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/financemetricscontainer-AutoDeployTrigger-981fb660-25d8-4b92-aa1f-632150e2bb70.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FINANCEMETRICSCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.FINANCEMETRICSCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINANCEMETRICSCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: financemetricscontainer
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: hub.docker.com/jonasferrao/financemetrics:${{ github.sha }}
          

     

